//! ⟡ Idea entity type
//! User-defined idea/seed tags for capturing conceptual seeds

define_entity_module! {
    Entity {
        UserDefined => "User-defined marker types",
    }
}

type IdeaDef = EntityDef;

pub fn get_entity_definitions() -> Vec<IdeaDef> {
    vec![
        IdeaDef {
            symbol: "⟡",
            name: "Idea",
            description: "User-defined idea marker for conceptual seeds",
            sort_order: 103,
            category: EntityCategory::UserDefined,
            lines: lines![
                ("≡", "idea marker ∧ conceptual seed"),
                ("≝", "nascent thought ∧ implementation potential"),
                ("∂", "∂ ERIS detection (not generated by entity recognition)"),
                ("⊛", "⟡⦑Symbol Migration⦒ | ⟡⦑Tag Hierarchy⦒ | ⟡⦑New Entity Type⦒"),
            ],
        },
    ]
}
