//! ⑀ Meta marker entity type
//! User-defined meta markers for arbitrary classification

define_entity_module! {
    Entity {
        UserDefined => "User-defined marker types",
    }
}

type MetaDef = EntityDef;

pub fn get_entity_definitions() -> Vec<MetaDef> {
    vec![
        MetaDef {
            symbol: "⑀",
            name: "Meta",
            description: "User-defined meta marker for arbitrary classification",
            sort_order: 100,
            category: EntityCategory::UserDefined,
            lines: lines![
                ("≡", "user status marker ∧ arbitrary classification"),
                ("≝", "flexible tagging ∧ user-defined semantics"),
                ("∂", "∂ ERIS detection (not generated by entity recognition)"),
                ("⊛", "⑀⦑Partial Tagging⦒ | ⑀⦑Interesting Phrase⦒ | ⑀⦑Review Later⦒"),
            ],
        },
    ]
}
