//! ◈ Project entity type
//! User-defined project/endeavor tags for organizing work

define_entity_module! {
    Entity {
        UserDefined => "User-defined marker types",
    }
}

type ProjectDef = EntityDef;

pub fn get_entity_definitions() -> Vec<ProjectDef> {
    vec![
        ProjectDef {
            symbol: "◈",
            name: "Project",
            description: "User-defined project marker for bounded endeavors",
            sort_order: 102,
            category: EntityCategory::UserDefined,
            lines: lines![
                ("≡", "project marker ∧ bounded endeavor"),
                ("≝", "scoped work ∧ goal-oriented activity"),
                ("∂", "∂ ERIS detection (not generated by entity recognition)"),
                ("⊛", "◈⦑Rustwise⦒ | ◈⦑ERIS Migration⦒ | ◈⦑Tag Validation⦒"),
            ],
        },
    ]
}
