//! § Section entity type
//! User-defined section marker for project/document divisions

define_entity_module! {
    Entity {
        UserDefined => "User-defined marker types",
    }
}

type SectionDef = EntityDef;

pub fn get_entity_definitions() -> Vec<SectionDef> {
    vec![
        SectionDef {
            symbol: "§",
            name: "Section",
            description: "User-defined section marker for document divisions",
            sort_order: 104,
            category: EntityCategory::UserDefined,
            lines: lines![
                ("≡", "section marker ∧ document division"),
                ("≝", "bounded scope ∧ organizational unit"),
                ("∂", "∂ ERIS detection (not generated by entity recognition)"),
                ("⊛", "§⦑Introduction⦒ | ◈§⦑Project⦒⦑Chapter 2⦒"),
            ],
        },
    ]
}
